// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3vXKy2DJjaJ6yGx28u9rvJc9DqBCSF48',
    appId: '1:480039567368:web:5934fed5cc6a0cb26811bd',
    messagingSenderId: '480039567368',
    projectId: 'amsys-768ac',
    authDomain: 'amsys-768ac.firebaseapp.com',
    storageBucket: 'amsys-768ac.appspot.com',
    measurementId: 'G-F4WJT7897S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChMIn0XHLz96pRuBX13ztxiotJ7Qu5oWk',
    appId: '1:480039567368:android:de51dbe81a6475ce6811bd',
    messagingSenderId: '480039567368',
    projectId: 'amsys-768ac',
    storageBucket: 'amsys-768ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFOrdYkCcgQwjqNNhwm1TKO31j2t9N8Y',
    appId: '1:480039567368:ios:1e8423f5571463ca6811bd',
    messagingSenderId: '480039567368',
    projectId: 'amsys-768ac',
    storageBucket: 'amsys-768ac.appspot.com',
    iosBundleId: 'com.example.fingerPrint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFOrdYkCcgQwjqNNhwm1TKO31j2t9N8Y',
    appId: '1:480039567368:ios:1e8423f5571463ca6811bd',
    messagingSenderId: '480039567368',
    projectId: 'amsys-768ac',
    storageBucket: 'amsys-768ac.appspot.com',
    iosBundleId: 'com.example.fingerPrint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3vXKy2DJjaJ6yGx28u9rvJc9DqBCSF48',
    appId: '1:480039567368:web:fbb9a5e08a541ed56811bd',
    messagingSenderId: '480039567368',
    projectId: 'amsys-768ac',
    authDomain: 'amsys-768ac.firebaseapp.com',
    storageBucket: 'amsys-768ac.appspot.com',
    measurementId: 'G-REPRM2HKC1',
  );
}
